package Hibernate;
// Generated 09.12.2016 10:52:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ActivityReport generated by hbm2java
 */
public class ActivityReport  implements java.io.Serializable {


     private Integer activityReportId;
     private Activity activity;
     private Date activityStartTime;
     private Date activityEndTime;

    public ActivityReport() {
    }

    public ActivityReport(Activity activity, Date activityStartTime, Date activityEndTime) {
       this.activity = activity;
       this.activityStartTime = activityStartTime;
       this.activityEndTime = activityEndTime;
    }
   
    public Integer getActivityReportId() {
        return this.activityReportId;
    }
    
    public void setActivityReportId(Integer activityReportId) {
        this.activityReportId = activityReportId;
    }
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }
    public Date getActivityStartTime() {
        return this.activityStartTime;
    }
    
    public void setActivityStartTime(Date activityStartTime) {
        this.activityStartTime = activityStartTime;
    }
    public Date getActivityEndTime() {
        return this.activityEndTime;
    }
    
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }




}


