package Hibernate;
// Generated 09.12.2016 13:25:19 by Hibernate Tools 4.3.1


import java.sql.Timestamp;
import java.util.Date;

/**
 * ActivityReport generated by hbm2java
 */
public class ActivityReport  implements java.io.Serializable {


     private Integer activityReportId;
     private Activity activity;
     private Timestamp activityStartTime;
     private Timestamp activityEndTime;
     private String activityDescription;

    public ActivityReport() {
    }

    public ActivityReport(Activity activity, Timestamp activityStartTime, Timestamp activityEndTime, String activityDescription) {
       this.activity = activity;
       this.activityStartTime = activityStartTime;
       this.activityEndTime = activityEndTime;
       this.activityDescription = activityDescription;
    }
   
    public Integer getActivityReportId() {
        return this.activityReportId;
    }
    
    public void setActivityReportId(Integer activityReportId) {
        this.activityReportId = activityReportId;
    }
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }
    public Date getActivityStartTime() {
        return this.activityStartTime;
    }
    
    public void setActivityStartTime(Timestamp activityStartTime) {
        this.activityStartTime = activityStartTime;
    }
    public Date getActivityEndTime() {
        return this.activityEndTime;
    }
    
    public void setActivityEndTime(Timestamp activityEndTime) {
        this.activityEndTime = activityEndTime;
    }
    public String getActivityDescription() {
        return this.activityDescription;
    }
    
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription;
    }




}


