package Hibernate;
// Generated 09.12.2016 16:25:05 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ActivityReport generated by hbm2java
 */
public class ActivityReport  implements java.io.Serializable {


     private Integer activityReportId;
     private Activity activity;
     private Date activityStartTime;
     private Date activityEndTime;
     private String activityDescription;
     private Integer activityDuration;

    public ActivityReport() {
    }

    public ActivityReport(Activity activity, Date activityStartTime, Date activityEndTime, String activityDescription, Integer activityDuration) {
       this.activity = activity;
       this.activityStartTime = activityStartTime;
       this.activityEndTime = activityEndTime;
       this.activityDescription = activityDescription;
       this.activityDuration = activityDuration;
    }
   
    public Integer getActivityReportId() {
        return this.activityReportId;
    }
    
    public void setActivityReportId(Integer activityReportId) {
        this.activityReportId = activityReportId;
    }
    public Activity getActivity() {
        return this.activity;
    }
    
    public void setActivity(Activity activity) {
        this.activity = activity;
    }
    public Date getActivityStartTime() {
        return this.activityStartTime;
    }
    
    public void setActivityStartTime(Date activityStartTime) {
        this.activityStartTime = activityStartTime;
    }
    public Date getActivityEndTime() {
        return this.activityEndTime;
    }
    
    public void setActivityEndTime(Date activityEndTime) {
        this.activityEndTime = activityEndTime;
    }
    public String getActivityDescription() {
        return this.activityDescription;
    }
    
    public void setActivityDescription(String activityDescription) {
        this.activityDescription = activityDescription;
    }
    public Integer getActivityDuration() {
        return this.activityDuration;
    }
    
    public void setActivityDuration(Integer activityDuration) {
        this.activityDuration = activityDuration;
    }




}


